# Generated by Django 5.2.7 on 2025-10-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='fullname',
        ),
    ]
