# Generated by Django 5.2.7 on 2025-11-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_fullname_attendance_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.duty'),
        ),
    ]
