# Generated by Django 5.2.7 on 2025-11-17 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_attendance_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.duty'),
        ),
    ]
