# Generated by Django 5.2.7 on 2025-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_attendance_status_adminaccesskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccesskey',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
