# Generated by Django 6.0 on 2025-12-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_adminaccesskey_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('blood_type', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('staff_id', models.TextField(blank=True, null=True)),
                ('work_schedule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_profiles',
                'managed': False,
            },
        ),
    ]
