# Generated by Django 5.2.7 on 2025-12-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_adminaccesskey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('security', 'Security Guard'), ('janitor', 'Janitor'), ('admin', 'Administrator')], max_length=50),
        ),
    ]
