# Generated by Django 5.2.7 on 2025-12-04 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_customuser_fullname_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='role',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='assigned_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='myapp.duty'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
        migrations.RunSQL(
            'ALTER TABLE myapp_duty ALTER COLUMN time_start TYPE timestamp with time zone USING date_trunc(\'day\', CURRENT_TIMESTAMP) + "time_start"',
            reverse_sql='ALTER TABLE myapp_duty ALTER COLUMN time_start TYPE time without time zone USING "time_start"::time',
        ),
        migrations.RunSQL(
            'ALTER TABLE myapp_duty ALTER COLUMN time_end TYPE timestamp with time zone USING date_trunc(\'day\', CURRENT_TIMESTAMP) + "time_end"',
            reverse_sql='ALTER TABLE myapp_duty ALTER COLUMN time_end TYPE time without time zone USING "time_end"::time',
        ),
    ]
