# Generated by Django 6.0 on 2025-12-08 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('name', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.TextField(null=True)),
                ('nationality', models.TextField(null=True)),
                ('blood_type', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('emergency_contact', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('staff_id', models.TextField(null=True)),
                ('work_schedule', models.TextField(null=True)),
                ('role', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
            ],
        ),
    ]
